version: "3"

services:
  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: yobasystems/alpine-mariadb:latest
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sql_blog_soft_delete
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./sql/001_employee.sql:/docker-entrypoint-initdb.d/001_employee.sql
      - ./sql/002_employee_group.sql:/docker-entrypoint-initdb.d/002_employee_group.sql
